const allQuestionsData = {
    "abdominalPain": {
        "title": "Abdominal Pain & General Examination",
        "questions": [
            { "id": "abdominalPain-q1", "text": "Describe the anatomical lines used to divide the abdomen into 9 regions." },
            { "id": "abdominalPain-q2", "text": "Provide a detailed analysis of pain using the SOCRATES mnemonic." },
            { "id": "abdominalPain-q3", "text": "Provide a detailed analysis of vomiting." },
            { "id": "abdominalPain-q4", "text": "If a patient has pain, when is it visible and how is the abdomen divided for examination?" },
            { "id": "abdominalPain-q5", "text": "Where does heartburn occur (epigastric/chest)? List associated diseases like peptic ulcer." },
            { "id": "abdominalPain-q6", "text": "Describe hematemesis according to severity, with examples." },
            { "id": "abdominalPain-q7", "text": "Differentiate between radiating and shifting pain." },
            { "id": "abdominalPain-q8", "text": "Explain why pain from acute appendicitis or cholecystitis might radiate to the shoulder." },
            { "id": "abdominalPain-q9", "text": "What is the appropriate extent of abdominal exposure for an examination and why?" },
            { "id": "abdominalPain-q10", "text": "What is the normal range for bilirubin? Differentiate between clinical and subclinical jaundice." },
            { "id": "abdominalPain-q11", "text": "In an abdominal exam of a patient lying on their left side, what is the proper procedure?" },
            { "id": "abdominalPain-q12", "text": "Explain the pathophysiology of guarding." },
            { "id": "abdominalPain-q13", "text": "In pain analysis, which is more important: site or severity? (duplicated)" },
            { "id": "abdominalPain-q14", "text": "What is the differential diagnosis for pain in each of the nine abdominal sites?" },
            { "id": "abdominalPain-q15", "text": "How and why do you measure the radial pulse in a patient with abdominal pain?" },
            { "id": "abdominalPain-q16", "text": "During abdominal pain, do bowel sounds increase, decrease, or remain normal? Why?" },
            { "id": "abdominalPain-q17", "text": "What is an 'aggravating factor' in the context of abdominal pain?" },
            { "id": "abdominalPain-q18", "text": "What is the significance of asking about past blood transfusions in a surgical history?" },
            { "id": "abdominalPain-q19", "text": "Differentiate between abdominal rigidity and guarding. (duplicated)" },
            { "id": "abdominalPain-q20", "text": "In an abdominal exam, what do you look for in the pulse?" },
            { "id": "abdominalPain-q21", "text": "What are the generations of cephalosporins?" },
            { "id": "abdominalPain-q22", "text": "In a patient with a diabetic foot, what is the role and procedure for a full abdominal examination?" },
            { "id": "abdominalPain-q23", "text": "Describe the effects of Diabetes Mellitus on the abdomen and the types of vessels it affects (small, middle, large)." },
            { "id": "abdominalPain-q24", "text": "Explain the patient's normal position during an abdominal examination and its rationale." },
            { "id": "abdominalPain-q25", "text": "Define gradual pain, colicky pain, and melena." },
            { "id": "abdominalPain-q26", "text": "Describe the characteristics of pain that radiates to the Right Iliac Fossa (RIF) and its likely cause (vagus nerve involvement)." },
            { "id": "abdominalPain-q27", "text": "Why does fever typically rise in abdominal pathologies?" },
            { "id": "abdominalPain-q28", "text": "List the intra-peritoneal and retro-peritoneal organs of the abdomen." },
            { "id": "abdominalPain-q29", "text": "What are the two main types of pain specific to the digestive system?" },
            { "id": "abdominalPain-q30", "text": "What specific questions should be included in a gynecological history (para, gravida, abortion)?" },
            { "id": "abdominalPain-q31", "text": "How do you perform a clinical examination for anemia, jaundice, and edema?" },
            { "id": "abdominalPain-q32", "text": "What is the correct procedure for performing a deep palpation on a post-operative patient?" },
            { "id": "abdominalPain-q33", "text": "Explain the clinical significance of supraclavicular lymphadenopathy (Virchow's node) in relation to GI malignancies." },
            { "id": "abdominalPain-q34", "text": "What is the appropriate management for a patient presenting with epigastric pain and vomiting without bleeding, but with a history of a bleeding ulcer?" }
        ]
    },
    "anorectal": {
        "title": "Anorectal",
        "questions": [
            { "id": "anorectal-q1", "text": "List the different types of anal fissures." },
            { "id": "anorectal-q2", "text": "Provide a classification for hemorrhoids." },
            { "id": "anorectal-q3", "text": "Describe the steps and expected findings of a digital rectal exam (DRE)." },
            { "id": "anorectal-q4", "text": "Provide the full classification, grades, clinical features, and management of hemorrhoids." },
            { "id": "anorectal-q5", "text": "Provide the full classification, clinical feature, and management of an anal fissure." },
            { "id": "anorectal-q6", "text": "Define and outline the treatment for an anal fistula." },
            { "id": "anorectal-q7", "text": "List the grades of hemorrhoids and the treatment for each. (duplicated)" },
            { "id": "anorectal-q8", "text": "Define sinus and fistula, providing clinical examples." }
        ]
    },
    "appendicitis": {
        "title": "Appendicitis",
        "questions": [
            { "id": "appendicitis-q1", "text": "What are the causes of intestinal obstruction secondary to acute appendicitis?" },
            { "id": "appendicitis-q2", "text": "What is the neurological differential diagnosis for acute appendicitis?" },
            { "id": "appendicitis-q3", "text": "Explain the pathophysiology of pain shifting from the peri-umbilical region to the right iliac fossa (RIF)." },
            { "id": "appendicitis-q4", "text": "What are the key investigations for a patient with suspected appendicitis?" },
            { "id": "appendicitis-q5", "text": "Describe the typical features of appendicitis on X-ray and ultrasound." },
            { "id": "appendicitis-q6", "text": "Is intravenous contrast necessary for a CT scan in suspected appendicitis?" },
            { "id": "appendicitis-q7", "text": "If all investigations are negative but the patient remains in severe pain, what is the next step in management?" },
            { "id": "appendicitis-q8", "text": "List the urological conditions that can mimic the pain of acute appendicitis." },
            { "id": "appendicitis-q9", "text": "What is the differential diagnosis of acute appendicitis?" },
            { "id": "appendicitis-q10", "text": "If appendicitis is suspected but a urinary stone is also a possibility, how do you confirm the diagnosis?" },
            { "id": "appendicitis-q11", "text": "What is the appropriate management for a patient presenting with a tender appendicular mass?" },
            { "id": "appendicitis-q12", "text": "Describe the different types of surgical incisions used for an appendectomy." },
            { "id": "appendicitis-q13", "text": "How does one perform and interpret the psoas sign?" },
            { "id": "appendicitis-q14", "text": "What are the contraindications for an appendectomy?" },
            { "id": "appendicitis-q15", "text": "What is the differential diagnosis for right iliac fossa pain in an unmarried 20-year-old female?" },
            { "id": "appendicitis-q16", "text": "What is the differential diagnosis for a child presenting with right iliac fossa pain and a cough?" },
            { "id": "appendicitis-q17", "text": "How can you differentiate appendicitis from an appendicular abscess if a patient's pain and fever persist post-operatively?" },
            { "id": "appendicitis-q18", "text": "What is the differential diagnosis for appendicitis in a 6-year-old child?" },
            { "id": "appendicitis-q19", "text": "What is Meckel's diverticulum and how can it mimic appendicitis? (duplicated)" },
            { "id": "appendicitis-q20", "text": "If a patient has abdominal pain, does it definitively mean they have appendicitis?" },
            { "id": "appendicitis-q21", "text": "How do you differentiate between acute pyelonephritis and appendicitis based on clinical findings?" },
            { "id": "appendicitis-q22", "text": "Is a loss of appetite (anorexia) a significant finding in patients with appendicitis? Why or why not?" },
            { "id": "appendicitis-q23", "text": "Can a perforated peptic ulcer present similarly to appendicitis?" },
            { "id": "appendicitis-q24", "text": "What are the typical X-ray findings in a patient with appendicitis? (duplicated)" },
            { "id": "appendicitis-q25", "text": "Why is a thorough surgical history important before performing an appendectomy?" },
            { "id": "appendicitis-q26", "text": "Why might a midline incision be chosen for a complicated case of appendicitis?" },
            { "id": "appendicitis-q27", "text": "A patient presents with a 4-year history of acute appendicitis symptoms, while another 20-year-old male presents with acute symptoms. Which case should be prioritized for surgery and why?" },
            { "id": "appendicitis-q28", "text": "What is the correct medical term for the surgical removal of the appendix?" },
            { "id": "appendicitis-q29", "text": "Is it safe to perform deep palpation on a patient who has recently undergone surgery?" },
            { "id": "appendicitis-q30", "text": "What nerve could be injured, causing a patient to limp on their right side after an appendectomy?" },
            { "id": "appendicitis-q31", "text": "What is the most important historical information to obtain from a patient who previously underwent an appendectomy?" },
            { "id": "appendicitis-q32", "text": "How can one differentiate between acute appendicitis and a ureteric stone?" },
            { "id": "appendicitis-q33", "text": "Why is pain shifting a key feature in the diagnosis of appendicitis?" },
            { "id": "appendicitis-q34", "text": "What type of intravenous fluid should be administered to a patient before an appendectomy and why?" },
            { "id": "appendicitis-q35", "text": "What is the appropriate management if a post-appendectomy patient develops abdominal distention, fever, and nausea?" },
            { "id": "appendicitis-q36", "text": "Describe the types of appendicitis." },
            { "id": "appendicitis-q37", "text": "Explain why pain from appendicitis increases with movement." },
            { "id": "appendicitis-q38", "text": "What do the combined symptoms of vomiting, constipation, and abdominal distention suggest?" },
            { "id": "appendicitis-q39", "text": "What antibiotics are typically given for appendicitis and what is their rationale?" },
            { "id": "appendicitis-q40", "text": "What are the signs of appendicitis in the extreme age groups (neonates and elderly) and why do they differ?" },
            { "id": "appendicitis-q41", "text": "What is the arterial supply of the appendix?" },
            { "id": "appendicitis-q42", "text": "How does one differentiate between acute appendicitis and ectopic pregnancy?" },
            { "id": "appendicitis-q43", "text": "Is a physical examination sign of tenderness at McBurney's point specific for appendicitis?" },
            { "id": "appendicitis-q44", "text": "How does the presentation of diarrhea or constipation differ in a patient with acute appendicitis and why?" },
            { "id": "appendicitis-q45", "text": "Describe the different anatomical positions of the appendix." }
        ]
    },
    "bariatric": {
        "title": "Bariatric Surgery",
        "questions": [
            { "id": "bariatric-q1", "text": "Define bariatric surgery and provide the classification of obesity according to BMI." },
            { "id": "bariatric-q2", "text": "What are the contraindications for bariatric surgery?" },
            { "id": "bariatric-q3", "text": "What are the common complications of a gastric lap band?" },
            { "id": "bariatric-q4", "text": "What are the differences between a gastric lap band and a vertical banded gastroplasty?" }
        ]
    },
    "breast": {
        "title": "Breast",
        "questions": [
            { "id": "breast-q1", "text": "Outline the complete management of a patient presenting with a breast mass that has metastasized to the lung with a super-added bacterial infection." },
            { "id": "breast-q2", "text": "How do you diagnose breast cancer by inspection?" },
            { "id": "breast-q3", "text": "How do you diagnose breast cancer by palpation?" },
            { "id": "breast-q4", "text": "How do you test for pectoral muscle fixation in a breast mass examination?" },
            { "id": "breast-q5", "text": "What are the risk factors that aggravate the severity of breast cancer?" },
            { "id": "breast-q6", "text": "What is the differential diagnosis for a breast lump other than cancer?" },
            { "id": "breast-q7", "text": "Describe the presentation, discharge characteristics, and risk factors for duct ectasia." },
            { "id": "breast-q8", "text": "What is the significance of nipple discharge in assessing breast pathology?" },
            { "id": "breast-q9", "text": "What is the relationship between menarche, breastfeeding, and the risk of breast cancer?" },
            { "id": "breast-q10", "text": "How are lung and liver metastases from breast cancer diagnosed?" },
            { "id": "breast-q11", "text": "What are the immediate and long-term complications of a modified radical mastectomy?" },
            { "id": "breast-q12", "text": "How do you test for long thoracic nerve injury (winged scapula) post-mastectomy?" },
            { "id": "breast-q13", "text": "What is the role of surgery in the management of metastatic breast cancer?" },
            { "id": "breast-q14", "text": "What is the staging of breast cancer that has metastasized to the lung?" },
            { "id": "breast-q15", "text": "Outline the triple assessment for a 35-year-old female complaining of a breast lump." },
            { "id": "breast-q16", "text": "What are the key historical points to cover in a patient with a breast lump (e.g., estrogen exposure, menarche, menopause, family history)?" },
            { "id": "breast-q17", "text": "What changes in the nipple can occur with breast pathology?" },
            { "id": "breast-q18", "text": "Describe the classification of breast cancer." },
            { "id": "breast-q19", "text": "What are the indications for a spleenectomy? (duplicated)" },
            { "id": "breast-q20", "text": "How do you prepare a patient for a spleenectomy, including necessary vaccinations?" },
            { "id": "breast-q21", "text": "What is the role of ultrasound and mammography in differentiating between benign and malignant breast masses?" },
            { "id": "breast-q22", "text": "Describe the blood supply of the breast." },
            { "id": "breast-q23", "text": "What artery is commonly harvested from the breast area for use in a CABG procedure?" },
            { "id": "breast-q24", "text": "How do you clinically differentiate between a benign and malignant breast mass based on discharge characteristics?" },
            { "id": "breast-q25", "text": "Explain the pathophysiology of peau d'orange." },
            { "id": "breast-q26", "text": "What are the surgical levels of axillary lymph nodes?" },
            { "id": "breast-q27", "text": "Describe the lymphatic drainage of the breast. (duplicated)" },
            { "id": "breast-q28", "text": "What are the top 4 most important risk factors for breast cancer?" },
            { "id": "breast-q29", "text": "How do you assess a patient with fibrocystic disease of the breast?" },
            { "id": "breast-q30", "text": "What nerves are at risk of injury during a mastectomy? (duplicated)" },
            { "id": "breast-q31", "text": "What is the difference between a lumpectomy and a mastectomy?" },
            { "id": "breast-q32", "text": "Describe the boundaries of the breast." }
        ]
    },
    "burns": {
        "title": "Burns",
        "questions": [
            { "id": "burns-q1", "text": "What are the key prognostic factors in a burn patient?" },
            { "id": "burns-q2", "text": "A patient with a 3-day-old burn develops hematemesis and dehydration. What is the likely cause? (Curling's ulcer)" },
            { "id": "burns-q3", "text": "Is a Curling's ulcer a true ulcer or an erosion?" },
            { "id": "burns-q4", "text": "What is the pathophysiology behind the formation of stress ulcers (erosions) in burn patients?" },
            { "id": "burns-q5", "text": "How would you manage a burn patient who develops a GI bleed?" },
            { "id": "burns-q6", "text": "If a recovering burn patient suddenly develops a new problem after eating solid food, what should you suspect?" },
            { "id": "burns-q7", "text": "A child is scalded with hot water on the chest and lower limb and has been vomiting for two days. What is the cause of the vomiting and how do you stop it?" },
            { "id": "burns-q8", "text": "What are the indications for hospital admission for a burn patient?" },
            { "id": "burns-q9", "text": "Describe the different types of intravenous fluids used in burn resuscitation and explain their differences." },
            { "id": "burns-q10", "text": "Explain the Parkland formula for fluid resuscitation in burn patients." },
            { "id": "burns-q11", "text": "How do you differentiate between burn patients who need ICU admission versus ward admission?" },
            { "id": "burns-q12", "text": "How should a doctor respond to a family's inquiry about a burn patient's prognosis? What is the basis for your answer?" },
            { "id": "burns-q13", "text": "What is the appropriate emergency management for a patient with severe burns?" },
            { "id": "burns-q14", "text": "How do you manage a patient with a severe burn?" },
            { "id": "burns-q15", "text": "What are the different types of burns and their classifications?" },
            { "id": "burns-q16", "text": "Describe the management of an electrical burn." },
            { "id": "burns-q17", "text": "How does a burn lead to acute tubular necrosis?" },
            { "id": "burns-q18", "text": "Define intussusception and state its most common cause." },
            { "id": "burns-q19", "text": "How many degrees of burns are there?" },
            { "id": "burns-q20", "text": "What is the pathognomonic feature of a third-degree burn?" },
            { "id": "burns-q21", "text": "What is syndactyly?" },
            { "id": "burns-q22", "text": "What are vascular malformations and how do they differ from hemangiomas?" },
            { "id": "burns-q23", "text": "How do you manage a hemangioma?" }
        ]
    },
    "criticalCare": {
        "title": "Critical Care & Resuscitation",
        "questions": [
            { "id": "criticalCare-q1", "text": "What fluids are used in resuscitation, and which is considered the best?" },
            { "id": "criticalCare-q2", "text": "In a patient with COVID-19 who develops a tension pneumothorax, what is the immediate management?" },
            { "id": "criticalCare-q3", "text": "What is a pulse deficit?" },
            { "id": "criticalCare-q4", "text": "Define phlegmasia alba dolens and phlegmasia cerulea dolens." },
            { "id": "criticalCare-q5", "text": "What is the standard management for chest trauma based on ABC principles?" },
            { "id": "criticalCare-q6", "text": "Can a hydatid cyst occur in the heart?" },
            { "id": "criticalCare-q7", "text": "Enumerate the causes of pancreatitis. (duplicated)" },
            { "id": "criticalCare-q8", "text": "What two primary tests are used to diagnose pancreatitis?" },
            { "id": "criticalCare-q9", "text": "What is obstructive shock, its mechanism, and its management?" },
            { "id": "criticalCare-q10", "text": "Describe the different types and stages of shock." },
            { "id": "criticalCare-q11", "text": "How do you manage a patient in shock, categorized by type?" },
            { "id": "criticalCare-q12", "text": "How do you assess the shock state using only blood pressure?" },
            { "id": "criticalCare-q13", "text": "Describe the pathophysiology of hypovolemic and cardiogenic shock." },
            { "id": "criticalCare-q14", "text": "Which medical professional (intern or anesthesiologist) is responsible for inserting an endotracheal tube?" },
            { "id": "criticalCare-q15", "text": "What are the complications of a bypass procedure?" },
            { "id": "criticalCare-q16", "text": "What is the role of a chest tube in managing chest trauma?" }
        ]
    },
    "emergencyTrauma": {
        "title": "Emergency & Trauma (ATLS)",
        "questions": [
            { "id": "emergencyTrauma-q1", "text": "How do you manage an unconscious patient with a suspected cervical spine injury presenting to the ER?" },
            { "id": "emergencyTrauma-q2", "text": "What is an oropharyngeal airway and what is its common name among nurses?" },
            { "id": "emergencyTrauma-q3", "text": "How do you manage a conscious patient with multiple injuries admitted to the ER?" },
            { "id": "emergencyTrauma-q4", "text": "A child sustains a depressed skull fracture after a fall, with a fluctuating level of consciousness. What is the diagnosis and immediate management?" },
            { "id": "emergencyTrauma-q5", "text": "A patient presents with a shortened and internally rotated leg after a road traffic accident (RTA). What is the likely diagnosis?" },
            { "id": "emergencyTrauma-q6", "text": "How do you manage a patient with a linear skull fracture in the temporal bone but a GCS of 15?" },
            { "id": "emergencyTrauma-q7", "text": "What is ATLS (Advanced Trauma Life Support) and what are its core components?" },
            { "id": "emergencyTrauma-q8", "text": "List the six life-threatening conditions in the chest that must be identified during the primary survey." },
            { "id": "emergencyTrauma-q9", "text": "How do you manage an open pneumothorax?" },
            { "id": "emergencyTrauma-q10", "text": "When should a chest tube be removed, and how do you confirm it's no longer needed?" },
            { "id": "emergencyTrauma-q11", "text": "What is the immediate management for a patient with an RTA who presents with blood at the urethral meatus and inability to void?" },
            { "id": "emergencyTrauma-q12", "text": "How do you manage a patient with a pelvic crash in the ER?" },
            { "id": "emergencyTrauma-q13", "text": "Describe the management of a patient with a traumatic pelvic fracture, including necessary imaging." },
            { "id": "emergencyTrauma-q14", "text": "What is the appropriate management for a patient with trauma and a tension pneumothorax?" },
            { "id": "emergencyTrauma-q15", "text": "Describe the management of a young patient with a femur fracture in an emergency department setting." },
            { "id": "emergencyTrauma-q16", "text": "What is the definition and management of a bullet injury according to emergency protocols?" },
            { "id": "emergencyTrauma-q17", "text": "Describe the ABCDE components of the ATLS primary survey in detail." },
            { "id": "emergencyTrauma-q18", "text": "What is the definition and management of a flail chest?" },
            { "id": "emergencyTrauma-q19", "text": "What are the indications for external fixation in trauma?" },
            { "id": "emergencyTrauma-q20", "text": "What is the management for a patient with a compound fracture, including IV antibiotic choice and dosage?" },
            { "id": "emergencyTrauma-q21", "text": "What is the immediate management for a patient with RTA?" },
            { "id": "emergencyTrauma-q22", "text": "Describe the examination and management of lower limb trauma, including the anatomical positions of key pulses." },
            { "id": "emergencyTrauma-q23", "text": "If a patient with a lower limb injury has a vascular compromise, where do you start the vascular examination (proximal or distal)?" },
            { "id": "emergencyTrauma-q24", "text": "What are the different methods for stabilizing a non-fractured bone injury (e.g., splint, functional brace)?" },
            { "id": "emergencyTrauma-q25", "text": "How do you perform a jaw thrust maneuver?" },
            { "id": "emergencyTrauma-q26", "text": "What is the appropriate initial amount of fluid to give a trauma patient?" },
            { "id": "emergencyTrauma-q27", "text": "What should you do if you do not have a cervical collar available for a trauma patient?" },
            { "id": "emergencyTrauma-q28", "text": "What is the next step if you cannot control bleeding in a chest trauma patient?" },
            { "id": "emergencyTrauma-q29", "text": "What are the causes of upper airway obstruction and its management?" },
            { "id": "emergencyTrauma-q30", "text": "What are the signs and management of a cardiac tamponade?" },
            { "id": "emergencyTrauma-q31", "text": "What is 'Adam-Stokes breathing'?" },
            { "id": "emergencyTrauma-q32", "text": "What are the indications for chest tube insertion? (duplicated)" },
            { "id": "emergencyTrauma-q33", "text": "How do you perform a neurological examination, including checking for a Babinski sign?" },
            { "id": "emergencyTrauma-q34", "text": "How do you manage a patient with an upper airway obstruction when standard methods fail in an emergency setting?" },
            { "id": "emergencyTrauma-q35", "text": "In a mass casualty incident with two patients—one talking and one choking—who is the higher priority?" }
        ]
    },
    "esophagusStomach": {
        "title": "Esophagus & Stomach",
        "questions": [
            { "id": "esophagusStomach-q1", "text": "What is the management for a patient with repeated heartburn and black, tarry stools, with a history of chronic NSAID use?" },
            { "id": "esophagusStomach-q2", "text": "Differentiate between peptic, gastric, and duodenal ulcers based on pathophysiology and clinical presentation." },
            { "id": "esophagusStomach-q3", "text": "Which is more serious, a gastric or duodenal ulcer, and why?" },
            { "id": "esophagusStomach-q4", "text": "What is the workup, investigation, and management for a patient with a gastric ulcer?" },
            { "id": "esophagusStomach-q5", "text": "What are the different types of gastric ulcers?" },
            { "id": "esophagusStomach-q6", "text": "What are the most accurate investigations for H. pylori infection?" },
            { "id": "esophagusStomach-q7", "text": "What are the benefits of endoscopy in managing upper GI conditions?" },
            { "id": "esophagusStomach-q8", "text": "What is melena, and what parts of the GI tract are considered 'upper'?" },
            { "id": "esophagusStomach-q9", "text": "What is the anatomical landmark that divides the upper and lower GI tract?" },
            { "id": "esophagusStomach-q10", "text": "What is the anatomical location of the Ampulla of Vater?" },
            { "id": "esophagusStomach-q11", "text": "What is achalasia and what are its key features?" },
            { "id": "esophagusStomach-q12", "text": "How do you manage a perforated peptic ulcer?" },
            { "id": "esophagusStomach-q13", "text": "Describe the clinical and radiological features of a perforated peptic ulcer." },
            { "id": "esophagusStomach-q14", "text": "Differentiate between a Mallory-Weiss tear and other causes of upper GI bleeding." },
            { "id": "esophagusStomach-q15", "text": "What is pyloric stenosis and what is its management?" },
            { "id": "esophagusStomach-q16", "text": "Describe the presentation and ultrasound findings of pyloric stenosis." },
            { "id": "esophagusStomach-q17", "text": "How do you medically and surgically treat a peptic ulcer?" },
            { "id": "esophagusStomach-q18", "text": "What are the differences between H2 blockers and Proton Pump Inhibitors (PPIs)?" },
            { "id": "esophagusStomach-q19", "text": "Describe the definitive diagnosis and indications for surgery in a patient with a peptic ulcer." }
        ]
    },
    "gallbladderBiliary": {
        "title": "Gallbladder & Biliary System",
        "questions": [
            { "id": "gallbladderBiliary-q1", "text": "How do you prepare a patient with obstructive jaundice for surgery?" },
            { "id": "gallbladderBiliary-q2", "text": "What are the key preparations needed for a patient with obstructive jaundice before surgery?" },
            { "id": "gallbladderBiliary-q3", "text": "What is the differential diagnosis for a patient who develops a fever after a cholecystectomy?" },
            { "id": "gallbladderBiliary-q4", "text": "If a post-cholecystectomy patient develops signs of intestinal obstruction, what is the likely biliary-related cause?" },
            { "id": "gallbladderBiliary-q5", "text": "What are the sequelae of acute pancreatitis?" },
            { "id": "gallbladderBiliary-q6", "text": "What is the fate of gallstones if left untreated?" },
            { "id": "gallbladderBiliary-q7", "text": "Describe the anatomy and function of the gallbladder." },
            { "id": "gallbladderBiliary-q8", "text": "What are mucocele and empyema of the gallbladder, and how does perforation occur?" },
            { "id": "gallbladderBiliary-q9", "text": "Explain the pathophysiology of gallstone ileus, including the type of fistula formed and its common location." },
            { "id": "gallbladderBiliary-q10", "text": "What is the difference between bile produced in the liver and bile stored in the gallbladder?" },
            { "id": "gallbladderBiliary-q11", "text": "What are the complications of gallstones?" },
            { "id": "gallbladderBiliary-q12", "text": "What is the mechanism behind the development of gallbladder cancer?" },
            { "id": "gallbladderBiliary-q13", "text": "What are the different types of gallstones, and which is the most common?" },
            { "id": "gallbladderBiliary-q14", "text": "Describe the clinical presentation, investigation, and management of acute cholecystitis." },
            { "id": "gallbladderBiliary-q15", "text": "How do you perform and interpret Murphy's sign?" },
            { "id": "gallbladderBiliary-q16", "text": "Is endoscopic or open surgery better for cholecystitis, and why?" },
            { "id": "gallbladderBiliary-q17", "text": "What is the appropriate management for acute cholecystitis?" },
            { "id": "gallbladderBiliary-q18", "text": "How do you prepare a patient for a cholecystectomy?" },
            { "id": "gallbladderBiliary-q19", "text": "What is the role of Vitamin K in a pre-operative patient?" },
            { "id": "gallbladderBiliary-q20", "text": "Describe the management of a patient with cholecystitis, including the 'golden period' for surgery." },
            { "id": "gallbladderBiliary-q21", "text": "What is the role of antibiotics in managing cholecystitis?" },
            { "id": "gallbladderBiliary-q22", "text": "Define the different types of jaundice and their pathophysiology." },
            { "id": "gallbladderBiliary-q23", "text": "What are the signs and symptoms of obstructive jaundice?" },
            { "id": "gallbladderBiliary-q24", "text": "What are the key investigations for a patient with obstructive jaundice?" },
            { "id": "gallbladderBiliary-q25", "text": "What is the role of ERCP in both diagnosing and treating biliary conditions?" }
        ]
    },
    "headNeck": {
        "title": "Head & Neck",
        "questions": [
            { "id": "headNeck-q1", "text": "Describe the embryology and surgical management of a thyroglossal duct cyst." },
            { "id": "headNeck-q2", "text": "How is the neck divided into surgical triangles?" },
            { "id": "headNeck-q3", "text": "What is the differential diagnosis for a neck lump?" },
            { "id": "headNeck-q4", "text": "Describe the anatomy and function of the trigeminal nerve." },
            { "id": "headNeck-q5", "text": "What is the function of the parasympathetic fibers of the facial nerve?" },
            { "id": "headNeck-q6", "text": "What is the differential diagnosis for a submental lymph node enlargement?" },
            { "id": "headNeck-q7", "text": "What is the drainage pattern of the submental lymph nodes?" },
            { "id": "headNeck-q8", "text": "How do you perform a jaw thrust maneuver? (duplicated)" },
            { "id": "headNeck-q9", "text": "Describe the full clinical examination of the facial nerve." },
            { "id": "headNeck-q10", "text": "What structures divide the parotid gland?" },
            { "id": "headNeck-q11", "text": "What are the symptoms of a 7th cranial nerve (facial nerve) palsy?" },
            { "id": "headNeck-q12", "text": "What is the motor and sensory distribution of the facial nerve?" },
            { "id": "headNeck-q13", "text": "How do you manage a patient with a neck fracture?" },
            { "id": "headNeck-q14", "text": "What are the indications and complications of external fixation for a neck fracture?" },
            { "id": "headNeck-q15", "text": "What are the indications and complications of a tracheostomy?" },
            { "id": "headNeck-q16", "text": "Describe the different parts of a metallic tracheostomy tube." },
            { "id": "headNeck-q17", "text": "What is the post-operative care for a patient with a tracheostomy?" },
            { "id": "headNeck-q18", "text": "How do you differentiate between a thyroglossal duct cyst and a thyroid swelling?" },
            { "id": "headNeck-q19", "text": "What is the management for a patient who is unable to breathe through their tracheostomy tube?" },
            { "id": "headNeck-q20", "text": "What is the management of epistaxis?" },
            { "id": "headNeck-q21", "text": "What is the differential diagnosis for a midline neck swelling?" },
            { "id": "headNeck-q22", "text": "How do you perform a clinical examination to differentiate a thyroid mass from other neck swellings?" }
        ]
    },
    "hernias": {
        "title": "Hernias",
        "questions": [
            { "id": "hernias-q1", "text": "A patient develops a hernia post-operatively. What type is it and why did it occur?" },
            { "id": "hernias-q2", "text": "Describe the boundaries of the femoral and inguinal canals." },
            { "id": "hernias-q3", "text": "List the types of hernias." },
            { "id": "hernias-q4", "text": "How do you examine a patient for a hernia?" },
            { "id": "hernias-q5", "text": "What are the indications for hernia surgery?" },
            { "id": "hernias-q6", "text": "How do you clinically identify a strangulated hernia?" },
            { "id": "hernias-q7", "text": "What is the three-finger test for hernias?" },
            { "id": "hernias-q8", "text": "What is the invagination test for hernias?" },
            { "id": "hernias-q9", "text": "Differentiate between a hernia and a hydrocele." },
            { "id": "hernias-q10", "text": "Describe the differences between a direct and an indirect inguinal hernia based on their anatomical source and path of descent." },
            { "id": "hernias-q11", "text": "What is the management of an incisional hernia?" },
            { "id": "hernias-q12", "text": "What is the definition of a femoral hernia?" },
            { "id": "hernias-q13", "text": "In a patient with an inguinal hernia, what does the presence of a cough impulse signify?" },
            { "id": "hernias-q14", "text": "What are the contents of the inguinal canal?" },
            { "id": "hernias-q15", "text": "What are the borders of Hesselbach's triangle?" },
            { "id": "hernias-q16", "text": "What are the anatomical relations of the inguinal canal?" },
            { "id": "hernias-q17", "text": "What is the most common type of hernia?" },
            { "id": "hernias-q18", "text": "Which type of hernia is more likely to become irreducible and strangulate faster than others?" },
            { "id": "hernias-q19", "text": "A patient presents with a hernia and diarrhea. Is there a likely association?" },
            { "id": "hernias-q20", "text": "What are the newer surgical treatments for hernias other than hernioraphy?" }
        ]
    },
    "intestinalObstruction": {
        "title": "Intestinal Obstruction",
        "questions": [
            { "id": "intestinalObstruction-q1", "text": "How do you manage a patient with intestinal obstruction (IO)?" },
            { "id": "intestinalObstruction-q2", "text": "What are the cardinal features of intestinal obstruction?" },
            { "id": "intestinalObstruction-q3", "text": "How do you differentiate intestinal obstruction based on history and examination?" },
            { "id": "intestinalObstruction-q4", "text": "Why is a direct anastomosis performed in the small bowel while a colostomy is often done in the large bowel for obstruction?" },
            { "id": "intestinalObstruction-q5", "text": "What are the typical X-ray features of small bowel versus large bowel obstruction?" },
            { "id": "intestinalObstruction-q6", "text": "Outline the management of a patient who develops intestinal obstruction 8 months after a partial gastrectomy." },
            { "id": "intestinalObstruction-q7", "text": "What is the management of intestinal obstruction in a neonate?" },
            { "id": "intestinalObstruction-q8", "text": "What is Meckel's diverticulum?" },
            { "id": "intestinalObstruction-q9", "text": "Describe the different types of intestinal obstruction." },
            { "id": "intestinalObstruction-q10", "text": "What are the causes of intestinal obstruction?" },
            { "id": "intestinalObstruction-q11", "text": "What is a bezoar?" },
            { "id": "intestinalObstruction-q12", "text": "How does a patient with intestinal obstruction present?" },
            { "id": "intestinalObstruction-q13", "text": "What is the role of an X-ray in diagnosing intestinal obstruction?" },
            { "id": "intestinalObstruction-q14", "text": "What type of intravenous fluid should be given to a patient with intestinal obstruction?" },
            { "id": "intestinalObstruction-q15", "text": "What is the significance of the color of a patient's vomitus in intestinal obstruction?" },
            { "id": "intestinalObstruction-q16", "text": "How do you manage hypokalemia in a patient with intestinal obstruction?" },
            { "id": "intestinalObstruction-q17", "text": "What is a PR exam and what is its role in a patient with intestinal obstruction?" },
            { "id": "intestinalObstruction-q18", "text": "A patient is 3 days post-operative and develops signs of obstruction. What is the likely cause?" },
            { "id": "intestinalObstruction-q19", "text": "What are the causes of a dynamic and adynamic intestinal obstruction?" },
            { "id": "intestinalObstruction-q20", "text": "How do you manage a patient with intestinal obstruction in an emergency setting?" }
        ]
    },
    "intussusception": {
        "title": "Intussusception",
        "questions": [
            { "id": "intussusception-q1", "text": "Can intussusception occur as a post-operative complication?" },
            { "id": "intussusception-q2", "text": "What are the prognostic factors in a patient with intussusception?" },
            { "id": "intussusception-q3", "text": "What is the common age group for intussusception?" },
            { "id": "intussusception-q4", "text": "What is the characteristic 'red currant jelly' stool in intussusception composed of?" },
            { "id": "intussusception-q5", "text": "What is the most common cause of intussusception in children versus adults?" },
            { "id": "intussusception-q6", "text": "What is the role of a 'leading point' in adult intussusception?" },
            { "id": "intussusception-q7", "text": "What is the classic clinical presentation of a child with intussusception?" },
            { "id": "intussusception-q8", "text": "What is the management of intussusception?" }
        ]
    },
    "largeIntestine": {
        "title": "Large Intestine (Colon & Rectum)",
        "questions": [
            { "id": "largeIntestine-q1", "text": "Why is a direct anastomosis performed in the small bowel while a colostomy is often done in the large bowel for obstruction? (duplicated)" },
            { "id": "largeIntestine-q2", "text": "Describe the clinical presentation, investigation, and management of ascending versus sigmoid colon cancer." },
            { "id": "largeIntestine-q3", "text": "Which is diagnosed later and has a poorer prognosis: sigmoid or ascending colon cancer?" },
            { "id": "largeIntestine-q4", "text": "Describe the morphology of colorectal cancer." },
            { "id": "largeIntestine-q5", "text": "What is the most common site for colonic cancer?" },
            { "id": "largeIntestine-q6", "text": "A patient has a colostomy and presents with signs of obstruction. What is the likely cause?" },
            { "id": "largeIntestine-q7", "text": "What are the indications for, and complications of, a stoma?" },
            { "id": "largeIntestine-q8", "text": "Compare and contrast the key features of ulcerative colitis and Crohn's disease." }
        ]
    },
    "liver": {
        "title": "Liver",
        "questions": [
            { "id": "liver-q1", "text": "How are liver metastases from breast cancer diagnosed?" },
            { "id": "liver-q2", "text": "Describe the presentation and management of a ruptured hydatid cyst in the lung." },
            { "id": "liver-q3", "text": "What is the causative organism of a hydatid cyst?" },
            { "id": "liver-q4", "text": "What is the most common organ affected by a hydatid cyst?" },
            { "id": "liver-q5", "text": "Describe the life cycle of Echinococcus granulosus." },
            { "id": "liver-q6", "text": "Are humans the final or intermediate host for Echinococcus granulosus?" },
            { "id": "liver-q7", "text": "What is the management of a hydatid cyst?" },
            { "id": "liver-q8", "text": "What is the most common type of cyst found in the liver?" },
            { "id": "liver-q9", "text": "Describe the layers of a hydatid cyst, including the parasite layer." }
        ]
    },
    "orthopedics": {
        "title": "Orthopedics & Fractures",
        "questions": [
            { "id": "orthopedics-q1", "text": "What is compartment syndrome and what are its detailed clinical features?" },
            { "id": "orthopedics-q2", "text": "List the different types of hip dislocations and identify the most common type." },
            { "id": "orthopedics-q3", "text": "What are the clinical signs of a sciatic nerve injury?" },
            { "id": "orthopedics-q4", "text": "Classify femoral neck fractures and describe their management (intracapsular vs. extracapsular)." },
            { "id": "orthopedics-q5", "text": "A 43-year-old female presents with a ruptured hemorrhagic ovarian cyst. What is the orthopedic relevance?" },
            { "id": "orthopedics-q6", "text": "Provide the classification for a supracondylar fracture." },
            { "id": "orthopedics-q7", "text": "In a supracondylar fracture, which artery is most at risk of damage?" },
            { "id": "orthopedics-q8", "text": "What are the symptoms of compartment syndrome? (duplicated)" },
            { "id": "orthopedics-q9", "text": "What nerve injury is commonly associated with a femur fracture?" },
            { "id": "orthopedics-q10", "text": "What are the unacceptable features (signs of malunion) in a pediatric femur fracture?" },
            { "id": "orthopedics-q11", "text": "Provide the Danis-Weber classification for malleolar fractures." },
            { "id": "orthopedics-q12", "text": "What is the mechanism of injury for an external rotation ankle fracture?" },
            { "id": "orthopedics-q13", "text": "What is a Galeazzi fracture?" },
            { "id": "orthopedics-q14", "text": "What is the appropriate management for a 32-year-old patient with a femoral shaft fracture: medical or surgical?" },
            { "id": "orthopedics-q15", "text": "Provide the classification for a tibial plateau fracture." },
            { "id": "orthopedics-q16", "text": "What are the common complications of a posterior hip dislocation?" },
            { "id": "orthopedics-q17", "text": "Describe the key features and management of a Colles' fracture." },
            { "id": "orthopedics-q18", "text": "What are the early signs of compartment syndrome? (duplicated)" },
            { "id": "orthopedics-q19", "text": "How many compartments are in the lower limb?" },
            { "id": "orthopedics-q20", "text": "Define a compound fracture." },
            { "id": "orthopedics-q21", "text": "A patient presents to the ER with an RTA and an unconscious state, along with a lower limb fracture. Outline the management according to ABCDE principles." },
            { "id": "orthopedics-q22", "text": "Differentiate between malunion and non-union of bones." },
            { "id": "orthopedics-q23", "text": "Provide the classifications for a Gastilo fracture." },
            { "id": "orthopedics-q24", "text": "Describe the clinical presentation of a radial nerve injury." },
            { "id": "orthopedics-q25", "text": "What is the anatomical pathway of the radial nerve?" },
            { "id": "orthopedics-q26", "text": "What are the predisposing factors for a plateau fracture?" },
            { "id": "orthopedics-q27", "text": "Compare and contrast Galeazzi and Monteggia fractures." },
            { "id": "orthopedics-q28", "text": "What is a Monteggia fracture?" },
            { "id": "orthopedics-q29", "text": "Describe the classification of a femoral head fracture." },
            { "id": "orthopedics-q30", "text": "What is the clinical presentation of a sciatic nerve injury? (duplicated)" },
            { "id": "orthopedics-q31", "text": "What is the clinical presentation and management of a humerus head fracture?" },
            { "id": "orthopedics-q32", "text": "What is the definition of a Galeazzi fracture? (duplicated)" },
            { "id": "orthopedics-q33", "text": "What are the general and local complications of fractures?" },
            { "id": "orthopedics-q34", "text": "What are the indications for internal versus external fixation?" },
            { "id": "orthopedics-q35", "text": "What is the management of a patient with a compound fracture, including IV antibiotic choice and dosage? (duplicated)" },
            { "id": "orthopedics-q36", "text": "Describe the management of a patient with a suspected spinal injury." },
            { "id": "orthopedics-q37", "text": "How do you manage a patient with a suspected back slab injury?" },
            { "id": "orthopedics-q38", "text": "Describe the management of a tibial plateau fracture." },
            { "id": "orthopedics-q39", "text": "What is the appropriate management for a 32-year-old patient with a femoral shaft fracture: medical or surgical? (duplicated)" },
            { "id": "orthopedics-q40", "text": "What is the management for an ankle fracture?" },
            { "id": "orthopedics-q41", "text": "What is a callus fracture and how is it managed?" }
        ]
    },
    "pancreas": {
        "title": "Pancreas",
        "questions": [
            { "id": "pancreas-q1", "text": "What is the presentation of acute pancreatitis?" },
            { "id": "pancreas-q2", "text": "A patient presents with severe epigastric pain radiating to the back. What is the likely diagnosis, what historical points are key, and what is the management?" },
            { "id": "pancreas-q3", "text": "What is the typical time course for the rise in serum amylase in acute pancreatitis?" },
            { "id": "pancreas-q4", "text": "What investigations, other than serum amylase, are crucial in managing acute pancreatitis?" },
            { "id": "pancreas-q5", "text": "How do you manage a patient with acute pancreatitis who also has gallstones?" },
            { "id": "pancreas-q6", "text": "What are the emergency complications of acute pancreatitis, particularly shock?" },
            { "id": "pancreas-q7", "text": "What are Cullen's and Grey Turner's signs, and what is their pathophysiology?" },
            { "id": "pancreas-q8", "text": "What are the most common causes of pancreatitis?" },
            { "id": "pancreas-q9", "text": "Differentiate between acute and chronic pancreatitis in terms of treatment, investigation, and complications." },
            { "id": "pancreas-q10", "text": "What are the possible complications of a pancreatic pseudocyst, and does it always require surgery?" },
            { "id": "pancreas-q11", "text": "What is the pathophysiology of gallstone-induced pancreatitis?" },
            { "id": "pancreas-q12", "text": "What is the management of a pancreatic fistula?" }
        ]
    },
    "pediatricSurgery": {
        "title": "Pediatric Surgery",
        "questions": [
            { "id": "pediatricSurgery-q1", "text": "What is the differential diagnosis for projectile vomiting in children?" },
            { "id": "pediatricSurgery-q2", "text": "A preterm baby presents with bilious vomiting. What is your opinion on this finding?" },
            { "id": "pediatricSurgery-q3", "text": "Is it appropriate to use a Nasogastric Tube (NGT) in a child with intestinal obstruction?" },
            { "id": "pediatricSurgery-q4", "text": "Describe the key features of duodenal obstruction in a neonate, including the amount and color of vomitus." },
            { "id": "pediatricSurgery-q5", "text": "What is the name of the surgical procedure for duodenal obstruction?" },
            { "id": "pediatricSurgery-q6", "text": "Describe the surgical management of meconium ileus." },
            { "id": "pediatricSurgery-q7", "text": "What is paralytic ileus, its signs, and its management?" },
            { "id": "pediatricSurgery-q8", "text": "How do you manage a pediatric patient with intestinal obstruction (IO)?" },
            { "id": "pediatricSurgery-q9", "text": "Define a fistula and describe the different types of nipple discharge and their significance." },
            { "id": "pediatricSurgery-q10", "text": "Describe the presentation and ultrasound findings of pyloric stenosis. (duplicated)" },
            { "id": "pediatricSurgery-q11", "text": "What is the mechanism of regurgitation?" },
            { "id": "pediatricSurgery-q12", "text": "Differentiate between the various types of hiatus hernias." },
            { "id": "pediatricSurgery-q13", "text": "Describe the management of a neonate with Hirschsprung's disease, including investigations and the role of rectal biopsy." },
            { "id": "pediatricSurgery-q14", "text": "What are the key features of congenital vascular malformations?" },
            { "id": "pediatricSurgery-q15", "text": "What are the common congenital malformations of the hand?" },
            { "id": "pediatricSurgery-q16", "text": "What is the appropriate timing for cleft lip and palate surgery and what are the potential complications?" }
        ]
    },
    "plasticSurgery": {
        "title": "Plastic Surgery & Skin Lesions",
        "questions": [
            { "id": "plasticSurgery-q1", "text": "Outline the complete assessment and management of a diabetic foot ulcer." },
            { "id": "plasticSurgery-q2", "text": "What is the difference between the base and the floor of an ulcer?" },
            { "id": "plasticSurgery-q3", "text": "How do you differentiate between a soft tissue infection and osteomyelitis in a diabetic foot?" },
            { "id": "plasticSurgery-q4", "text": "What are the different types of ulcers, and which type is most common in diabetic patients?" },
            { "id": "plasticSurgery-q5", "text": "What is the antibiotic of choice for a patient with a diabetic foot infection?" },
            { "id": "plasticSurgery-q6", "text": "How do you confirm the diagnosis of a basal cell carcinoma?" },
            { "id": "plasticSurgery-q7", "text": "From where should a biopsy of a suspected skin cancer be taken: the periphery or the center?" },
            { "id": "plasticSurgery-q8", "text": "What is the typical pattern of invasion for a basal cell carcinoma?" },
            { "id": "plasticSurgery-q9", "text": "Outline the treatment for a basal cell carcinoma." },
            { "id": "plasticSurgery-q10", "text": "Who is qualified to take a biopsy of a skin lesion?" },
            { "id": "plasticSurgery-q11", "text": "Differentiate between a squamous cell carcinoma (SCC) and a basal cell carcinoma (BCC) slide." },
            { "id": "plasticSurgery-q12", "text": "What is a skin flap?" },
            { "id": "plasticSurgery-q13", "text": "A patient has a large, black lesion on their forehead. What is the differential diagnosis?" },
            { "id": "plasticSurgery-q14", "text": "What are the different types of skin tumors, and which is the most aggressive?" },
            { "id": "plasticSurgery-q15", "text": "How do you manage a 3x2 cm ulcer below the left eye?" },
            { "id": "plasticSurgery-q16", "text": "Differentiate between a hypertrophic scar and a keloid scar." },
            { "id": "plasticSurgery-q17", "text": "What is the management of a skin graft?" },
            { "id": "plasticSurgery-q18", "text": "What problems are associated with a cleft lip?" },
            { "id": "plasticSurgery-q19", "text": "What is the management of an electrical injury classification?" },
            { "id": "plasticSurgery-q20", "text": "What is a port-wine stain and how does it differ from a hemangioma?" }
        ]
    },
    "shock": {
        "title": "Shock",
        "questions": [
            { "id": "shock-q1", "text": "Define shock." },
            { "id": "shock-q2", "text": "List the different types of shock." },
            { "id": "shock-q3", "text": "How do you clinically differentiate between hypovolemic and neurogenic shock?" },
            { "id": "shock-q4", "text": "What is the mechanism of obstructive shock and how is it managed?" },
            { "id": "shock-q5", "text": "What is metabolic shock and how do you manage Diabetic Ketoacidosis (DKA)?" },
            { "id": "shock-q6", "text": "What are the different degrees of shock?" },
            { "id": "shock-q7", "text": "What are the similarities between anaphylactic shock and other forms of shock?" },
            { "id": "shock-q8", "text": "What are the causes of hypovolemic shock?" },
            { "id": "shock-q9", "text": "How do you differentiate neurogenic shock from other types?" },
            { "id": "shock-q10", "text": "Can septic shock cause bradycardia?" }
        ]
    },
    "spleen": {
        "title": "Spleen",
        "questions": [
            { "id": "spleen-q1", "text": "What are the indications for a splenectomy?" },
            { "id": "spleen-q2", "text": "What are the complications of a splenectomy?" },
            { "id": "spleen-q3", "text": "How do you clinically differentiate between splenomegaly and an enlarged kidney on palpation?" },
            { "id": "spleen-q4", "text": "In which conditions is a splenectomy curative (e.g., hereditary spherocytosis)?" },
            { "id": "spleen-q5", "text": "What pre-operative preparations, including vaccinations, are required for a splenectomy?" },
            { "id": "spleen-q6", "text": "A CT scan shows a splenic laceration. What is the management?" },
            { "id": "spleen-q7", "text": "What is the appropriate management for a traumatic splenic rupture?" },
            { "id": "spleen-q8", "text": "What is the indication for a splenectomy in a patient with Sickle Cell Anemia (SCA)?" },
            { "id": "spleen-q9", "text": "Is there any other procedure that must be performed concurrently with a splenectomy?" }
        ]
    },
    "surgicalInfections": {
        "title": "Surgical Infections & Wounds",
        "questions": [
            { "id": "surgicalInfections-q1", "text": "On which post-operative day does a wound infection typically manifest?" },
            { "id": "surgicalInfections-q2", "text": "What are the signs of a wound infection and how is it managed?" },
            { "id": "surgicalInfections-q3", "text": "Differentiate between a sterile and a contaminated wound, providing examples." },
            { "id": "surgicalInfections-q4", "text": "What are the clinical features and treatment of a wound infection?" },
            { "id": "surgicalInfections-q5", "text": "What are the requirements for a successful skin graft take?" },
            { "id": "surgicalInfections-q6", "text": "Describe the management of a wound infection with an associated ileostomy." },
            { "id": "surgicalInfections-q7", "text": "What is the difference between a primary, secondary, and tertiary wound?" },
            { "id": "surgicalInfections-q8", "text": "Differentiate between peritonitis and peritonism." },
            { "id": "surgicalInfections-q9", "text": "What are the different stages of wound closure?" },
            { "id": "surgicalInfections-q10", "text": "Describe the different types of suture materials used in abdominal surgery." },
            { "id": "surgicalInfections-q11", "text": "How does a post-operative wound infection develop, and how is it diagnosed and treated?" },
            { "id": "surgicalInfections-q12", "text": "Differentiate between an abscess and cellulitis." },
            { "id": "surgicalInfections-q13", "text": "How do you clean a wound?" },
            { "id": "surgicalInfections-q14", "text": "What is an open fracture?" },
            { "id": "surgicalInfections-q15", "text": "Differentiate between a keloid and a hypertrophic scar." }
        ]
    },
    "thyroidParathyroid": {
        "title": "Thyroid & Parathyroid",
        "questions": [
            { "id": "thyroidParathyroid-q1", "text": "What are the complications of a thyroidectomy, and when does hypocalcemia typically occur?" },
            { "id": "thyroidParathyroid-q2", "text": "What are the early signs of hypocalcemia (Chvostek's and Trousseau's signs)?" },
            { "id": "thyroidParathyroid-q3", "text": "What is the appropriate management for post-operative hypocalcemia?" },
            { "id": "thyroidParathyroid-q4", "text": "A post-thyroidectomy patient develops sudden respiratory distress. What is the likely cause and management?" },
            { "id": "thyroidParathyroid-q5", "text": "What is the appropriate management for a patient with a thyroid swelling?" },
            { "id": "thyroidParathyroid-q6", "text": "What investigations are required for a patient with a thyroid swelling?" },
            { "id": "thyroidParathyroid-q7", "text": "What are the indications for surgery in a patient with a thyroid swelling?" },
            { "id": "thyroidParathyroid-q8", "text": "Provide a classification for malignant thyroid tumors." },
            { "id": "thyroidParathyroid-q9", "text": "What are the histopathological features of papillary thyroid cancer?" },
            { "id": "thyroidParathyroid-q10", "text": "What are the tumor markers for medullary thyroid cancer?" },
            { "id": "thyroidParathyroid-q11", "text": "What is the association between lymphoma and Hashimoto's thyroiditis?" },
            { "id": "thyroidParathyroid-q12", "text": "A post-thyroidectomy patient presents with dyspnea. What is the cause and management of the cervical hematoma?" },
            { "id": "thyroidParathyroid-q13", "text": "Why does a slipped ligature cause a post-operative hematoma?" },
            { "id": "thyroidParathyroid-q14", "text": "What are the different types of goiter?" },
            { "id": "thyroidParathyroid-q15", "text": "What are the different types of thyroid cancer?" },
            { "id": "thyroidParathyroid-q16", "text": "What is the management of a thyrotoxicosis case that needs to be sent to the ENT department?" },
            { "id": "thyroidParathyroid-q17", "text": "Which type of thyroid tumor has a familial link?" },
            { "id": "thyroidParathyroid-q18", "text": "How do you prepare a patient with thyrotoxicosis to become euthyroid before surgery?" },
            { "id": "thyroidParathyroid-q19", "text": "What are the complications of a thyroidectomy? (duplicated)" },
            { "id": "thyroidParathyroid-q20", "text": "Why is it necessary to examine the vocal cords before performing a thyroid operation?" },
            { "id": "thyroidParathyroid-q21", "text": "A patient develops stridor and choking after a thyroid operation. What is the cause and immediate management?" }
        ]
    },
    "urology": {
        "title": "Urology",
        "questions": [
            { "id": "urology-q1", "text": "List the urological conditions that can mimic appendicitis pain. (duplicated)" },
            { "id": "urology-q2", "text": "What is the diagnosis and treatment for benign prostatic hyperplasia (BPH)?" },
            { "id": "urology-q3", "text": "Provide the classification, diagnosis, and treatment for prostate cancer." },
            { "id": "urology-q4", "text": "How do you differentiate between prostate cancer and BPH?" },
            { "id": "urology-q5", "text": "What percentage of the kidney is likely to be affected by a hydatid cyst?" },
            { "id": "urology-q6", "text": "A 75-year-old female presents with an abdominal mass and painless hematuria. What is the diagnosis and management?" },
            { "id": "urology-q7", "text": "What is the first step to confirm a diagnosis of bladder cancer?" },
            { "id": "urology-q8", "text": "What are the typical IVU findings in a patient with a bladder tumor?" },
            { "id": "urology-q9", "text": "What is a varicocele, what are its grades, and why is grading important?" },
            { "id": "urology-q10", "text": "How do you manage a patient with acute urinary retention?" },
            { "id": "urology-q11", "text": "What is the next step if you cannot insert a Foley catheter?" },
            { "id": "urology-q12", "text": "What is the procedure for a suprapubic cystostomy?" },
            { "id": "urology-q13", "text": "What is a ureterocele and what does it look like on an X-ray?" },
            { "id": "urology-q14", "text": "Differentiate between extraperitoneal and intraperitoneal bladder injuries. Which is more dangerous and why?" },
            { "id": "urology-q15", "text": "What are the most common causes of extraperitoneal bladder injury?" },
            { "id": "urology-q16", "text": "What is a bezoar? (duplicated)" },
            { "id": "urology-q17", "text": "How do you manage a patient with a 12 mm kidney stone?" },
            { "id": "urology-q18", "text": "What are the contraindications for ESWL?" },
            { "id": "urology-q19", "text": "List other treatment modalities for kidney stones." },
            { "id": "urology-q20", "text": "Describe the different grades of renal injury." },
            { "id": "urology-q21", "text": "How does a varicocele affect fertility?" },
            { "id": "urology-q22", "text": "What are the surgical indications and incision name for a varicocele repair?" },
            { "id": "urology-q23", "text": "What is the most common cause of UTI and what type of organism is it?" },
            { "id": "urology-q24", "text": "What is the difference between an upper and lower UTI?" },
            { "id": "urology-q25", "text": "Why is a Foley catheter inserted in a patient with intestinal obstruction?" },
            { "id": "urology-q26", "text": "What is the normal urine output?" },
            { "id": "urology-q27", "text": "Differentiate between anuria and urinary retention." },
            { "id": "urology-q28", "text": "What are the different types of kidney stones, and which are radiolucent versus radiopaque?" },
            { "id": "urology-q29", "text": "A patient presents with blood at the urethral meatus after an RTA. What is the likely diagnosis and management?" },
            { "id": "urology-q30", "text": "What is the management of urethral injury?" }
        ]
    },
    "vascular": {
        "title": "Vascular Surgery",
        "questions": [
            { "id": "vascular-q1", "text": "How do you manage a patient with a vascular injury?" },
            { "id": "vascular-q2", "text": "What are the hard signs of a vascular injury?" },
            { "id": "vascular-q3", "text": "Differentiate between a neuropathic ulcer and an arterial ulcer." },
            { "id": "vascular-q4", "text": "When examining a lower limb injury, should you start proximally or distally?" },
            { "id": "vascular-q5", "text": "In a vascular examination, do you proceed from proximal to distal or vice-versa?" },
            { "id": "vascular-q6", "text": "List the main arteries of the lower limb and their anatomical locations." },
            { "id": "vascular-q7", "text": "What is the significance of DVT in a patient with a ruptured hemorrhagic ovarian cyst?" },
            { "id": "vascular-q8", "text": "What are the signs of limb ischemia?" },
            { "id": "vascular-q9", "text": "Is there an occupational association with limb ischemia?" },
            { "id": "vascular-q10", "text": "How do you assess a patient with acute limb ischemia?" },
            { "id": "vascular-q11", "text": "What is the management of acute brain ischemia?" },
            { "id": "vascular-q12", "text": "What are the complications of varicose veins?" },
            { "id": "vascular-q13", "text": "What are the signs, symptoms, and management of DVT?" },
            { "id": "vascular-q14", "text": "Describe the key features of Raynaud's phenomenon and Raynaud's disease." },
            { "id": "vascular-q15", "text": "What is the appropriate management for vascular trauma to the lower leg, such as a popliteal artery injury?" },
            { "id": "vascular-q16", "text": "What is the best type of IV fluid for resuscitation in hemorrhagic shock?" },
            { "id": "vascular-q17", "text": "What are the causes of peripheral vascular injury and how is it managed?" },
            { "id": "vascular-q18", "text": "Outline the assessment of a 50-year-old male presenting with leg pain, including tests for arterial examination." },
            { "id": "vascular-q19", "text": "Define intermittent claudication." },
            { "id": "vascular-q20", "text": "Which areas of the foot are most commonly affected by arterial insufficiency and why?" },
            { "id": "vascular-q21", "text": "What investigations for vascular trauma are best for an emergency setting, and what do you look for on a Doppler ultrasound?" },
            { "id": "vascular-q22", "text": "Explain the ankle-brachial index (ABI) and its significance in diagnosing ischemia." },
            { "id": "vascular-q23", "text": "How do you assess a patient with an ischemic limb? (duplicated)" },
            { "id": "vascular-q24", "text": "Define varicose veins and outline their investigation." },
            { "id": "vascular-q25", "text": "Why is a Doppler ultrasound used in the assessment of varicose veins?" },
            { "id": "vascular-q26", "text": "Describe the surface marking of the anterior tibial, posterior tibial, and dorsalis pedis arteries." },
            { "id": "vascular-q27", "text": "If the dorsalis pedis pulse is absent, how do you differentiate between a pathological and a physiological variation?" }
        ]
    },
    "misc": {
        "title": "Miscellaneous OSCE Stations & General Questions",
        "questions": [
            { "id": "misc-q1", "text": "Describe the key components of a chest tube drainage system (UWS)." },
            { "id": "misc-q2", "text": "How do you confirm that a chest tube is functioning correctly?" },
            { "id": "misc-q3", "text": "What is the procedure for removing a chest tube?" },
            { "id": "misc-q4", "text": "Describe the method for removing surgical sutures." },
            { "id": "misc-q5", "text": "A patient in the recovery room has a stoma bag. Describe how you would assess it." },
            { "id": "misc-q6", "text": "An 84-year-old female has a urine bag. How can you be sure it contains urine and not other fluids like pus?" },
            { "id": "misc-q7", "text": "A patient is holding a 'happy birthday' balloon and blowing into it post-operatively. What is the likely clinical reason for this?" },
            { "id": "misc-q8", "text": "A patient has edema. How do you assess its extent?" },
            { "id": "misc-q9", "text": "First question: why didn't you prepare for the lecture? Why were you absent?" },
            { "id": "misc-q10", "text": "A patient has a picture of an internal fixation (screw and nail). What are the indications and complications?" },
            { "id": "misc-q11", "text": "What are the different types of continuous traction?" },
            { "id": "misc-q12", "text": "What are the indications for internal fixation? (duplicated)" },
            { "id": "misc-q13", "text": "What are the complications of skin traction versus skeletal traction?" },
            { "id": "misc-q14", "text": "What are the safe boundaries for chest tube insertion?" },
            { "id": "misc-q15", "text": "What is the indication for a chest tube, and which diseases might require pleurodesis?" },
            { "id": "misc-q16", "text": "In a mass casualty incident, how do you triage patients?" },
            { "id": "misc-q17", "text": "You are in the ER and a patient with a burn arrives. His relative asks you to explain the situation. How do you respond and on what basis do you provide your answer?" },
            { "id": "misc-q18", "text": "What are the different types and purposes of pink and green cannulas?" },
            { "id": "misc-q19", "text": "A married woman with no missed period complains of acute right iliac fossa pain. What is the differential diagnosis?" },
            { "id": "misc-q20", "text": "How do you calculate a patient's weight?" },
            { "id": "misc-q21", "text": "What type of blood do you prepare for a surgical patient and what tests are required?" },
            { "id": "misc-q22", "text": "What is the follow-up management after applying skin traction?" },
            { "id": "misc-q23", "text": "An X-ray shows an internal fixation. What are the names of the plate and screw used?" },
            { "id": "misc-q24", "text": "You are presented with a case on a laptop with a brief history. What is the diagnosis and what are the key findings? (Context: General OSCE station)" },
            { "id": "misc-q25", "text": "You are in an OSCE station with a patient who has a stethoscope. What are the key things to assess?" },
            { "id": "misc-q26", "text": "What is the correct procedure for examining a patient's abdomen without causing pain?" },
            { "id": "misc-q27", "text": "A patient has a neck lump. What is the differential diagnosis and what investigations are required? (duplicated)" },
            { "id": "misc-q28", "text": "What is the correct way to hold and use a stethoscope during an examination?" },
            { "id": "misc-q29", "text": "A patient is fully wrapped in a bandage with only their fingertips showing. How do you perform a vascular and neurological assessment?" }
        ]
    }
};
